// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.1
package dk.mydefence.mdif.common;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Defines the status of a request
   * </pre>
   *
   * Protobuf enum {@code mdif.common.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * The request was successful
     * </pre>
     *
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <pre>
     * The request failed
     * </pre>
     *
     * <code>FAILURE = 1;</code>
     */
    FAILURE(1),
    /**
     * <pre>
     * The request was invalid
     * </pre>
     *
     * <code>ERR_INVALID = 2;</code>
     */
    ERR_INVALID(2),
    /**
     * <pre>
     * The request is not supported
     * </pre>
     *
     * <code>ERR_NOT_SUPPORTED = 3;</code>
     */
    ERR_NOT_SUPPORTED(3),
    /**
     * <pre>
     * The request is not implemented
     * </pre>
     *
     * <code>ERR_NOT_IMPLEMENTED = 4;</code>
     */
    ERR_NOT_IMPLEMENTED(4),
    /**
     * <pre>
     * The device is not ready to process the request
     * </pre>
     *
     * <code>ERR_NOT_READY = 5;</code>
     */
    ERR_NOT_READY(5),
    /**
     * <pre>
     * The device cannot process the size
     * </pre>
     *
     * <code>ERR_SIZE = 6;</code>
     */
    ERR_SIZE(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * The request was successful
     * </pre>
     *
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <pre>
     * The request failed
     * </pre>
     *
     * <code>FAILURE = 1;</code>
     */
    public static final int FAILURE_VALUE = 1;
    /**
     * <pre>
     * The request was invalid
     * </pre>
     *
     * <code>ERR_INVALID = 2;</code>
     */
    public static final int ERR_INVALID_VALUE = 2;
    /**
     * <pre>
     * The request is not supported
     * </pre>
     *
     * <code>ERR_NOT_SUPPORTED = 3;</code>
     */
    public static final int ERR_NOT_SUPPORTED_VALUE = 3;
    /**
     * <pre>
     * The request is not implemented
     * </pre>
     *
     * <code>ERR_NOT_IMPLEMENTED = 4;</code>
     */
    public static final int ERR_NOT_IMPLEMENTED_VALUE = 4;
    /**
     * <pre>
     * The device is not ready to process the request
     * </pre>
     *
     * <code>ERR_NOT_READY = 5;</code>
     */
    public static final int ERR_NOT_READY_VALUE = 5;
    /**
     * <pre>
     * The device cannot process the size
     * </pre>
     *
     * <code>ERR_SIZE = 6;</code>
     */
    public static final int ERR_SIZE_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Status forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return FAILURE;
        case 2: return ERR_INVALID;
        case 3: return ERR_NOT_SUPPORTED;
        case 4: return ERR_NOT_IMPLEMENTED;
        case 5: return ERR_NOT_READY;
        case 6: return ERR_SIZE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dk.mydefence.mdif.common.Common.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:mdif.common.Status)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\013mdif.common*\204\001\n\006Status\022\013" +
      "\n\007SUCCESS\020\000\022\013\n\007FAILURE\020\001\022\017\n\013ERR_INVALID\020" +
      "\002\022\025\n\021ERR_NOT_SUPPORTED\020\003\022\027\n\023ERR_NOT_IMPL" +
      "EMENTED\020\004\022\021\n\rERR_NOT_READY\020\005\022\014\n\010ERR_SIZE" +
      "\020\006B\032\n\030dk.mydefence.mdif.commonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
